package chaincode

import "time"

// SubmissionState represents the lifecycle state of an artifact as provided by the API.
// It is intentionally a plain string alias to remain compatible with the gateway's enum.
type SubmissionState string

// ManifestItem describes a single file that is part of the artifact's manifest.
// Keep fields ordered for deterministic JSON serialization across languages.
type ManifestItem struct {
	Algorithm string `json:"algorithm"` // e.g. "sha256"
	Filename  string `json:"filename"`  // original filename
	Hash      string `json:"hash"`      // hex-encoded content hash
}

// Artifact represents the data the peer receives from the API to be persisted on-chain.
// All fields are provided by the API; the chaincode does not compute derived values at creation time.
// Keep fields ordered for deterministic JSON serialization across languages.
type Artifact struct {
	Acknowledgements  string          `json:"acknowledgements"`
	Dois              []string        `json:"dois"`
	Footprint         string          `json:"footprint"` // 64-char lowercase hex (sha256)
	FundingAgencies   []string        `json:"fundingAgencies"`
	ID                string          `json:"id"` // UUID generated by the gateway
	Keywords          []string        `json:"keywords"`
	LastTimeVerified  *time.Time      `json:"lastTimeVerified"`
	Links             []string        `json:"links"`
	Manifest          []ManifestItem  `json:"manifest"`
	SubmitterEmail    string          `json:"submitterEmail"`
	SubmitterUsername string          `json:"submitterUsername"`
	SubmissionState   SubmissionState `json:"submissionState,omitempty"`
	SubmittedAt       *time.Time      `json:"submittedAt"`
	Title             string          `json:"title"`
	Description       string          `json:"description"`
	Verified          bool            `json:"verified"`
}
